name: "Build and Test"
description: "Build and Test the application"
inputs:
  app-name:
    description: "Name of the image"
    required: false
    default: ${{ github.repository }}
  appid:
    description: "Application ID"
    required: false
    default: "0"
  orgid:
    description: "Organization ID"
    required: false
    default: "0"
  buid:
    description: "Business Unit ID"
    required: false
    default: "0"
  test-directory:
    description: "Directory containing tests"
    required: false
    default: "test"
  sonar-source-path:
    description: "Path to the source code for SonarQube scan"
    required: false
    default: "src"
  role-to-assume:
    description: "Role to assume"
    required: true
    type: string
  region:
    description: "Region"
    required: false
    default: "us-east-1"
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      id: install-dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Secrets Check
      id: secrets-check
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-secretscanner-workflow@v2
      with:
        github-token: ${{ github.token }}

    - name: SonarQube Check
      id: sonarqube-check
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-sonarscan-workflow@v1
      with:
        sonar-source-path: ${{ inputs.sonar-source-path }}

    - name: SAST Scan
      id: sast-scan
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-sast-workflow@v1
      with:
        language: python

    - name: Docker Build
      id: docker-build
      uses: orbitcluster/oc-cicd-docker-build-workflow@v1
      with:
        docker-build-path: .
        image-name: ${{ inputs.app-name }}
        appid: ${{ inputs.appid }}
        orgid: ${{ inputs.orgid }}
        buid: ${{ inputs.buid }}

    - name: Docker Push
      id: docker-push
      uses: orbitcluster/oc-cicd-docker-push-workflow@feat/push_init
      with:
        image-type: docker
        image-name: ${{ inputs.app-name }}
        tag: ${{ env.DOCKER_TAG }}
        appid: ${{ inputs.appid }}
        orgid: ${{ inputs.orgid }}
        buid: ${{ inputs.buid }}
