name: "Build and Test"
description: "Build and Test the application"
inputs:
  app-name:
    description: "Name of the image"
    required: false
    default: ${{ github.repository }}
  appid:
    description: "Application ID"
    required: false
    default: "0"
  orgid:
    description: "Organization ID"
    required: false
    default: "0"
  buid:
    description: "Business Unit ID"
    required: false
    default: "0"
  test-directory:
    description: "Directory containing tests"
    required: false
    default: "test"
  sonar-source-path:
    description: "Path to the source code for SonarQube scan"
    required: false
    default: "src"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Secrets Check
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-secretscanner-workflow@fix/accomodatewfcall
      with:
        github-token: ${{ github.token }}

    - name: SonarQube Check
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-sonarscan-workflow@fix/accomodatewfcall
      with:
        sonar-source-path: ${{ inputs.sonar-source-path }}

    - name: SAST Scan
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-sast-workflow@fix/accomodatewfcall
      with:
        language: python

    # - name: Docker Build
    #   uses: orbitcluster/oc-cicd-docker-build-workflow@feat/addinitialcode
    #   with:
    #     docker-build-path: .
    #     image-name: ${{ inputs.app-name }}
    #     appid: ${{ inputs.appid }}
    #     orgid: ${{ inputs.orgid }}
    #     buid: ${{ inputs.buid }}
