name: "Build and Test"
description: "Build and Test the application"
inputs:
  test-directory:
    description: "Directory containing tests"
    required: true
    default: "test"
  sonar-source-path:
    description: "Path to the source code for SonarQube scan"
    required: false
    default: "src"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Secrets Check
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-secretscanner-workflow@v2

    - name: SonarQube Check
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: orbitcluster/oc-cicd-sonarscan-workflow@v1
      with:
        sonar-source-path: ${{ inputs.sonar-source-path }}

